version: '3.3'
services:
  odoo:
    image: odoo:17.0
    #platform: linux/amd64 #Neede with M1 processors
    container_name: odoo_test_exercise
    restart: unless-stopped
    command: --dev xml
    ports:
      - 8069:8069
    depends_on:
      - db
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf:ro

  db:
    image: postgres:14
    container_name: postgres_odoo_test_exercise
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
volumes:
  odoo-web-data:
  odoo-db-data:
