-- Table setup
DROP TABLE IF EXISTS news_article;

CREATE TABLE news_article(
   id 				INT 	GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
   title        	VARCHAR,
   type        		VARCHAR,
   language_code    VARCHAR,
   country_code     VARCHAR
);

-- Populate the table with some data
INSERT INTO news_article (title, type, language_code, country_code) VALUES ('Article 1', 'politics', 'en_US', 'fi');
INSERT INTO news_article (title, type, language_code, country_code) VALUES ('Article 2', 'politics', 'en_US', 'ee');
INSERT INTO news_article (title, type, language_code, country_code) VALUES ('Article 3', 'politics', 'en_US', 'lv');
INSERT INTO news_article (title, type, language_code, country_code) VALUES ('Article 4', 'politics', 'en_US', 'lt');
INSERT INTO news_article (title, type, language_code, country_code) VALUES ('Article 5', 'politics', 'et_EE', 'fi');
INSERT INTO news_article (title, type, language_code, country_code) VALUES ('Article 6', 'politics', 'et_EE', 'ee');
INSERT INTO news_article (title, type, language_code, country_code) VALUES ('Article 7', 'politics', 'et_EE', 'lv');
INSERT INTO news_article (title, type, language_code, country_code) VALUES ('Article 8', 'politics', 'et_EE', 'lt');
INSERT INTO news_article (title, type, language_code, country_code) VALUES ('Article 9', 'science', 'en_US', 'fi');
INSERT INTO news_article (title, type, language_code, country_code) VALUES ('Article 10', 'science', 'en_US', 'ee');
INSERT INTO news_article (title, type, language_code, country_code) VALUES ('Article 11', 'science', 'en_US', 'lv');
INSERT INTO news_article (title, type, language_code, country_code) VALUES ('Article 12', 'science', 'en_US', 'lt');
INSERT INTO news_article (title, type, language_code, country_code) VALUES ('Article 13', 'science', 'et_EE', 'fi');
INSERT INTO news_article (title, type, language_code, country_code) VALUES ('Article 14', 'science', 'et_EE', 'ee');
INSERT INTO news_article (title, type, language_code, country_code) VALUES ('Article 15', 'science', 'et_EE', 'lv');
INSERT INTO news_article (title, type, language_code, country_code) VALUES ('Article 16', 'science', 'et_EE', 'lt');

-- Example SQL query from the excercise to test whether the table is set up correctly
SELECT * FROM news_article
WHERE 
news_article.type = 'science'
AND news_article.language_code != 'en_US'
AND (
    news_article.country_code = 'ee'
    OR news_article.country_code = 'lv'
    OR news_article.country_code = 'lt'
);
